### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by gustav901** [hBurt/runecrafting-tracker#1]
I've tried at Wrath alter, Mind alter and Ourania and none of them worked. None of the runes crafted was tracked.
The only "special" thing I can think of is that I have RC cape.

I would love for this plugin to work because it would be a lot of fun just keeping track.

**Comment by hBurt** [comment]
I haven't specifically tried the plugin at altars other than Ourania, but in theory it should have still worked. I will look more into this, but for now, once you are inside the Ourania altar area that is underground try restarting runelite(Closing the application and re-starting it) that seems to fix any problems I've had so far .

**Comment by gustav901** [comment]
# Tested in the following steps

## Having the plugin disabled, teleported and went down stairs in Ourania
Crafting the runes at the Ourania alter did not register in the plugin.

## Was by alter with the plugin enabled, restarted RuneLite
Crafting the runes at the Ourania alter did register in the plugin.

## Leaving Ourania, filling pouches and teleporting back to Ourania
Teleported to ToB, filled pouches, used teleport  and went down stairs and crafted runes. All the runes did register in the plugin.

## Left Ourania, filled pouches went to Wrath alter
Teleported to ToB, filled pouches, went home and teleported to Wrath alter and crafted Wrath runes. The Wrath runes did not register in the plugin.

## Went to bank, filled pouches and went back to Ourania
Teleported to ToB, filled pouches, used teleport  and went down stairs and crafted runes. All the runes did register in the plugin.

# Wrote the last part and logged back into the game at ToB
## Went to Ourania alter to look at the chat message when crafting runes there
Crafted the runes and they did register, but they were all added as "new entities". I now have 2 entries for all the different runes (2 fire, 2 air, ...). The value of the rune is the same (calculated the value / number of runes crafted), likely not the issue.
### The chat message (Game chat to On)
You bind the temple's power into runes.

## Went to Wrath alter to look at the chat message when crafting runes there
The runes did not register (no surprise).
### The chat message (Game chat to On)
You bind the temple's power into wrath runes.
___

While I have not programmed any plugin for RuneLite it appears (when exceptionally loosely scanning the code) it's reading a message from the chat?

As such, in additional information; I have the "Collapse Game Chat" option enabled in the Chat Filter plugin.

I also have the Ardy elite diary completed as such get the extra "Your medium level knowledge of the local area allows you to bind additional runes." message when I craft runes at Ourania.

Maybe this help guide your bug hunting.

**Comment by dickhead420** [comment]
Doesn't work for me either unfortunately. Running nats through the abyss. Tried closing/reopening runelite and reinstalling the plugins, didn't work.

**Comment by hBurt** [comment]
@gustav901 thank you for the information, I will look into this and see what might be causing the issue. @dickhead420 I will be looking into the errors to see what may be causing them. 

I cannot assure this will be fixed within the week but I will work when I am free so solve this problem, thank you for your input and patience.

**Comment by itsozone** [comment]
Works sometimes, and other times it doesnt. restarting while in the cave sometimes fixes it, but thats a bad thing to have to do everytime you want to use a plugin.

**Comment by MKuijpers** [comment]
@hBurt I am not sure if you are still active or reading this, but I would appreciate it if you could take a look at my PR and merge it if you approve.

I fixed the issues that broke the plugin, as well as some small UI updates.

**Comment by MKuijpers** [comment]
I decided to do some long tests with the plugin turned on. I have been runecrafting all day with the plugin enabled and it worked just as expected. I did not run into any issues during the whole day.
